default_platform(:ios)
      
#bundle_id: "com.example.wallace.poc-modulo",

platform :ios do
  desc "App Distribution Firebase"
  lane :distribute do
    sigh(force: true)
    
    build_app(
      workspace: "poc-modulo.xcworkspace",
      xcargs: "-allowProvisioningUpdates",
      configuration: "Debug",
      scheme: "poc-modulo"
    )
    
    firebase_app_distribution(
        app: "1:32788606712:ios:1bcc54eb466a9065b0d50d",
        testers: "wallace.baldenebre.daycoval@gmail.com",
        googleservice_info_plist_path: "GoogleService-Info.plist",
        service_credentials_file: "gc_keys.json",
        release_notes_file: "fastlane/release-notes.txt"
    )
  end
end
